version: "3.7"

services:
    web:
        build: 
            context: ./farm_app
            dockerfile: Dockerfile.prod
        command: gunicorn --worker-class eventlet --bind 0.0.0.0 -w 1 farm_app:app
        volumes:
            - static_volume:/home/farm_app/app/static
        expose:
            - 8000  
        env_file: 
            - ./.env.dev
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/farm_app/app/static
        ports:
            - 80:80
        depends_on: 
            - web
volumes:
    static_volume: