"""farms table

Revision ID: a043cd0a2bf4
Revises: 0ea43f6d9f2b
Create Date: 2020-01-09 13:02:35.303201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a043cd0a2bf4'
down_revision = '0ea43f6d9f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_user', sa.String(length=64), nullable=True),
    sa.Column('farm_date', sa.DateTime(), nullable=True),
    sa.Column('farm_cnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('farms_date_cnt_ix', 'farm', ['farm_date', 'farm_cnt'], unique=False)
    op.create_index(op.f('ix_farm_twitch_user'), 'farm', ['twitch_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_twitch_user'), table_name='farm')
    op.drop_index('farms_date_cnt_ix', table_name='farm')
    op.drop_table('farm')
    # ### end Alembic commands ###
